version: '2.0'

services:

  blogit:
    build: blogit/
    environment:
      - VIRTUAL_HOST=elixir-lang.bg,blog.elixir-lang.bg,elixir.app.astea.net
    expose:
      - "4000"
    restart: unless-stopped
    labels:
      maintainer: 'meddle <n.tzvetinov@gmail.com>'
      description: 'Elixir course'  
