version: '2.0'

services:

  blogit:
    build: blogit/
    expose:
      - "4000"
    restart: unless-stopped
  
  proxy:
    build: proxy/
    ports:
      - "80:80"
    restart: unless-stopped
    labels:
      maintainer: 'maintainer here'
      description: 'description here'
    depends_on:
      - blogit
